version: '3.8'

services:
  db:
    image: postgres:13
    container_name: autoboard_database
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: autoboard
    ports:
      - "5432:5432"  # Exposes PostgreSQL to the host machine
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build: .
    container_name: autoboard_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/autoboard
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
