name: Deploy to Elastic Beanstalk

on:
  push:
    branches: [ndzalama/feat/test-deployment]
    paths:
      - "pom.xml"
      - ".github/workflows/api-database.yml"
      - "flyway/**"
      - "terraform/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Build the project with Maven
        working-directory: ./api
        run: mvn clean package -DskipTests

      - name: Check
        run: ls -a api/target

      - name: Upload JAR
        # We upload so we can re-use same jar in next job.
        uses: actions/upload-artifact@v4
        with:
          # Name of artifact can be anything
          name: artifact
          # Relative path to jar file
          path: api/target/*.jar

  deploy:
    # Depends on build's job
    needs: build
    name: Deploy to Elastic Beanstalk
    # Will run steps on latest version of ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Download JAR
        # Download the artifact which was uploaded in the Build Archive's job
        uses: actions/download-artifact@v4
        with:
          name: artifact

      - name: Check Downloaded artifact
        run: ls -a ./

      - uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.RDS_IAM_USER_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.RDS_IAM_USER_SECRET_KEY }}
          region: ${{ secrets.AWS_REGION }}
          application_name: auto-board
          environment_name: auto-board-env
          version_label: "auto-board-${{ github.sha }}-${{ github.run_id }}"
          deployment_package: autoboard-0.0.1-SNAPSHOT.jar
