name: Build and Deploy Maven JAR to S3

on:
  push:
    branches:
      - '*'  # Trigger on pushes to any branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Java environment
    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'temurin' # Eclipse Temurin - supports JDK 21
        java-package: jdk
        architecture: x64

    # Build the Maven project
    - name: Build with Maven
      run: mvn clean install -DskipTests

    # Install AWS CLI
    - name: Install AWS CLI
      run: |
        sudo apt-get install -y python3-pip
        python3 -m pip install --upgrade awscli

    # Create S3 bucket if it doesn't exist
    - name: Ensure S3 bucket exists
      run: |
        aws s3api head-bucket --bucket ${{ secrets.BUCKET_NAME }} || aws s3 mb s3://${{ secrets.BUCKET_NAME }} --region ${{ secrets.AWS_REGION }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.RDS_IAM_USER_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.RDS_IAM_USER_SECRET_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}

    # Upload JAR to S3
    - name: Upload JAR to S3
      run: aws s3 cp ./target/autoboard-0.0.1-SNAPSHOT.jar s3://$BUCKET_NAME/${GITHUB_SHA:0:7}/ --region $AWS_REGION
      env:
        BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
        AWS_ACCESS_KEY_ID: ${{ secrets.RDS_IAM_USER_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.RDS_IAM_USER_SECRET_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
