name: Sonar test

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  TF_CLOUD_ORGANIZATION: "auto-board"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: "auto-board-github-actions"
  CONFIG_DIRECTORY: "./terraform"
  DB_USERNAME: "${{ secrets.DB_USERNAME }}"
  DB_PASSWORD: "${{ secrets.DB_PASSWORD }}"
  GOOGLE_SECRET: "${{ secrets.GOOGLE_CLIENT_SECRET }}"

permissions:
  id-token: write
  contents: read

jobs:
  sonarQubeApplication:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and analyze code quality
        working-directory: ./api
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=auto-board_auto-board \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.inclusions="src/**/*.java" \
            -Dsonar.exclusions="**/test/**" \
            -DskipTests
