name: Deploy application with Terraform

on:
  release:
    types: [published]

jobs:
  deploy_terraform:
    name: Deploy with terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws_access_key_id: ${{ secrets.RDS_IAM_USER_ACCESS_KEY }}
          aws_secret_access_key: ${{ secrets.RDS_IAM_USER_SECRET_KEY }}
          region: ${{ secrets.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Initialize terraform
        run: terraform init

      - name: Validate terraform configuration
        run: terraform validate -no-color

      - name: Run terraform apply
        run: terraform apply -auto-approve -no-color
